name: tdlook_flutter_app
description: XpertFit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.6+132

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: 3.7.12

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: 2.9.0
  firebase_analytics: 10.2.0
  firebase_crashlytics: 3.1.0
  firebase_performance: 0.9.1

  # Bloc
  bloc: 7.1.0
  flutter_bloc: 7.2.0
  get_it: 7.2.0
  injectable: 1.5.3
  
  # Media
  #camera: 0.9.4+19
  camera: 0.10.3+2
  video_player: 2.3.0
  audioplayers: 0.20.1

  # UI
  cupertino_icons: 1.0.4
  google_fonts: 3.0.1 #2.3.1
  flutter_launcher_icons: 0.9.2
  custom_sliding_segmented_control: 1.6.0
  flutter_native_splash: 2.1.6
  material_design_icons_flutter: 5.0.6595
  sensors: 2.0.3
  pull_to_refresh: 2.0.0
  pagination_view: 2.0.0
  pin_code_fields: 7.4.0
  scrollable_positioned_list: 0.3.2
  visibility_detector: 0.3.3
  webview_flutter_plus: 0.3.0+2

  # Common
  http: 0.13.4
  device_info_plus: 3.2.3
  package_info_plus: 1.4.2
  intl_utils: 2.6.1
  connectivity_plus: 2.3.0
  enum_to_string: 2.0.1
  shared_preferences: 2.0.15
  url_launcher: 6.1.10
  tuple: 2.0.0
  wakelock: 0.6.1+2
  permission_handler: 10.2.0
  web_socket_channel: 2.1.0
  logger: 1.1.0
  flutter_dotenv: 5.0.2
  flutter_multi_formatter: 2.5.8
  json_annotation: 4.5.0
  freezed_annotation: 2.0.3
  flutter_exif_rotation: 0.5.1
  open_store: 0.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
  #image_path: "assets/icon_backstage.png" # Backstage

flutter_native_splash:
  color: "#16181B"
  ios: false
  image: "assets/Splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.10
  # injectable_generator: 1.5.3
  json_serializable: 6.2.0
  freezed: 2.0.3+1

flutter_intl:
  enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/Resources/
    - assets/
    - assets/HandsFreeAudio/
    - assets/images/
    - .env/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
