// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_app.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6QvijrhSDS5g-RBsxHFHTwb_mEIh0nW8',
    appId: '1:780247890893:android:3d9fd6e289b6ce0153a284',
    messagingSenderId: '780247890893',
    projectId: 'xpertfit-3d149',
    storageBucket: 'xpertfit-3d149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBliO_GTKOZjeeEQ0ER4fnCVu7EnjOzqew',
    appId: '1:780247890893:ios:6a9c755ad405993053a284',
    messagingSenderId: '780247890893',
    projectId: 'xpertfit-3d149',
    storageBucket: 'xpertfit-3d149.appspot.com',
    androidClientId: '780247890893-6109j86l9mkibgubnhtpt7q6qjdqivbj.apps.googleusercontent.com',
    iosClientId: '780247890893-jchljcc3nqi8vr8u41s2tdgu7ec6q7tt.apps.googleusercontent.com',
    iosBundleId: 'com.project.xpertfit-backstage',
  );
}
